### Site Settings ###
title               : Siddhartha G
description         : >-
                      Software Engineer at BNY Mellon | IIT Tirupati CSE '24
baseurl             : ""            
repository          : S1ddh4rthaG/S1ddh4rthaG.github.io     
remote_theme        : yousinix/portfolYOU
open_new_tab        : true                    

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Siddhartha G
  image             : /assets/imgs/siddharthag-light.jpg
  # email             : siddhar7ha.g@gmail.com
  github            : S1ddh4rthaG
  linkedin          : siddharthag22
  x                 : s1ddhartha_g

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Analytics ###
analytics:
  enabled: true                                  # Set true to enable analytics
  google:
    tracking_id: G-V7P0S13VPV

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
